app:
    basepath: http://ehealth.yidudao.cn/cfd
    config: /opt/soft/link.properties
server:
    port: 80
    context-path: /cfd
spring:
    datasource:
        name: test
        url: jdbc:mysql://rm-2zevb68932k92lm39.mysql.rds.aliyuncs.com:3306/health?autoReconnect=true&amp;characterEncoding=utf-8
        username: root
        password: A@20181029
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 1
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    mvc:
        static-path-pattern: /**
    resources:
        static-locations: classpath:/public/
            
mybatis:
    mapper-locations: classpath:mapping/*.xml,classpath*:mapping/custom/*.xml
    type-aliases-package: com.breeze.health.entity

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

wexin:
    appid: wxb3fa58ce48e65eca
    appsecret: 1c64c98c2dc51a03e2b7c254f2abba03
    token: 698D51A19D8A121CE581499D7B701668
sms:
    appid: 1400154159
    appkey: aa37534c94ed0224f955d4e215245ff5